name: Typing Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/*
  workflow_dispatch:

jobs:
  typing-check:
    name: Typing Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          path: Doors

      - name: Checkout world-portals
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: AmyJeanes/world-portals
          ref: main
          path: world-portals

      - name: Checkout wire
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: wiremod/wire
          ref: master
          path: wire

      - name: Checkout gmod-addon-tools
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          repository: AmyJeanes/gmod-addon-tools
          # renovate: datasource=github-tags depName=AmyJeanes/gmod-addon-tools
          ref: v0.27.0
          path: gmod-addon-tools

      - name: Run typing check
        working-directory: Doors
        shell: pwsh
        run: ./scripts/typing-check.ps1
